server:
  port: 8088
  servlet:
    context-path: /chat

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  profiles:
    active: dev
  application:
    name: wechat-mvc
  mail:
    username: luo.wenjie@foxmail.com
    password: iufklnyicrqgcdja
    host: smtp.qq.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: io.github.tomhusky.wechatmvc.server.*.entity

web-socket-mvc:
  basePackage: io.github.tomhusky.wechatmvc.server.session.controller
  enable-valid: true