file:
  rootPath: D:\\mnt\\docker\\nginx\\www\\wechat\\
  baseUrl: http://127.0.0.1/wechat/
  groupPath: nocache\\img\\group\\
  groupUrl: nocache/img/group/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_mvc?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1